 const tmoData = {
            nex110: {
                'AA02H0': { tempo: 5, desc: 'Motor Completo OH' },
                'AA04R0': { tempo: 5, desc: 'Carcaça do Motor Completa' },
                'AB09R0': { tempo: 0.6, desc: 'Tampa Cabeote' },
                'AB20R0': { tempo: 1.6, desc: 'Junta Cabeçote Completo' },
                'AB21R0': { tempo: 1.2, desc: 'Junta do Cabeçote um lado' },
                'AC03R0': { tempo: 1.4, desc: 'Cilindro e Juntas Um lado' },
                'AE01R0': { tempo: 4.5, desc: 'Virabrequim' },
                'AE11R0': { tempo: 4.6, desc: 'Rolamento do Virabrequim LD' },
                'AE19R0': { tempo: 0.9, desc: 'Retentor do Virabrequim LD' },
                'AE20R0': { tempo: 0.6, desc: 'Retentor do Virabrequim LE' },
                'AE24R0': { tempo: 4.5, desc: 'Balanceiro do Virabrequim' },
                'AE27R0': { tempo: 1, desc: 'Engrenagem Primária do Virabrequim' },
                'AF01R0': { tempo: 1.5, desc: 'Pistão, Pino e Anéis' },
                'AG02R0': { tempo: 1.2, desc: 'Válvula, Molas e Retentores' },
                'AG08R0': { tempo: 0.8, desc: 'Balanceiro de Válvulas' },
                'AH02R0': { tempo: 0.9, desc: 'Comando de Válvulas' },
                'AH04R0': { tempo: 1.4, desc: 'Corrente de comando' },
                'AH06R0': { tempo: 0.3, desc: 'Ajustador da Corrente de Comando' },
                'AH13R0': { tempo: 1, desc: 'Tensor da Corrente de Comando' },
                'BA01R0': { tempo: 1, desc: 'Bomba de óleo Completa' },
                'BA04R0': { tempo: 1.4, desc: 'Engrenagem Condutora Bomba óleo' },
                'BA05R0': { tempo: 1.5, desc: 'Engrenagem Conduzida Bomba óleo' },
                'BB02R0': { tempo: 0.2, desc: 'Filtro de óleo' },
                'BB04R0': { tempo: 0.6, desc: 'Tanque de óleo' },
                'DA05R0': { tempo: 0.5, desc: 'Coletor de Admissão' },
                'DA15R0': { tempo: 0.3, desc: 'Cano de Escape Central' },
                'DA26R0': { tempo: 0.3, desc: 'Escapamento um lado' },
                'DB01R0': { tempo: 0.5, desc: 'Filtro de Ar Completo' },
                'DB06R0': { tempo: 0.2, desc: 'Elemento Filtrante' },
                'DC02H0': { tempo: 0.7, desc: 'Carburador Completo OH' },
                'DC18R0': { tempo: 0.3, desc: 'Cabo do Afogador' },
                'DC25R0': { tempo: 0.4, desc: 'Cabo do Acelerador' },
                'DH01R0': { tempo: 0.6, desc: 'Tanque de Combustível' },
                'DH05R0': { tempo: 0.1, desc: 'Tampa do Tanque' },
                'DH06R0': { tempo: 0.3, desc: 'Registro de Combustível' },
                'DH11R0': { tempo: 0.4, desc: 'Mangueira Combustível Registro-Carburador' },
                'EA01R0': { tempo: 0.4, desc: 'Bateria' },
                'EA02R0': { tempo: 0.5, desc: 'Suporte da Bateria' },
                'EA07R0': { tempo: 0.5, desc: 'Cabo Terra da Bateria' },
                'EB01R0': { tempo: 0.5, desc: 'Bobina de Ignição' },
                'EB09R0': { tempo: 0.6, desc: 'Unidade de Ignição' },
                'EB21R0': { tempo: 0.1, desc: 'Vela de Ignição' },
                'EB22R0': { tempo: 0.2, desc: 'Supressor de Vela' },
                'EE01R0': { tempo: 0.6, desc: 'Motor de Partida Completo' },
                'EE05R0': { tempo: 0.6, desc: 'Relé de Partida' },
                'EG01R0': { tempo: 0.6, desc: 'Rotor Magneto' },
                'EG03R0': { tempo: 0.7, desc: 'Estator' },
                'EG12R0': { tempo: 0.6, desc: 'Tampa do Magneto' },
                'GA03R0': { tempo: 0.9, desc: 'Embreagem Completa' },
                'GA06R0': { tempo: 0.7, desc: 'Embreagem Completa e Carcaça' },
                'GA27R0': { tempo: 0.5, desc: 'Tampa da Embreagem' },
                'GA28R0': { tempo: 0.6, desc: 'Cabo de Embreagem' },
                'GA32R0': { tempo: 0.4, desc: 'Manete de Embreagem' },
                'GB01R0': { tempo: 0.6, desc: 'Jogo de Embreagem de Partida' },
                'GJ01R0': { tempo: 4.5, desc: 'Partes Internas da Transmissão' },
                'GK01R0': { tempo: 5, desc: 'Seletor de Marchas' },
                'GK02R0': { tempo: 0.2, desc: 'Pedal de Câmbio' },
                'GK03R0': { tempo: 0.7, desc: 'Eixo do Pedal' },
                'GS01R0': { tempo: 0.3, desc: 'Pinho do Motor' },
                'GS02R0': { tempo: 0.4, desc: 'Corrente de Transmissão' },
                'GS04R0': { tempo: 0.6, desc: 'Coroa de Transmissão' },
                'GS35R0': { tempo: 0.2, desc: 'Tampa do Pinho' },
                'HE01R0': { tempo: 1.5, desc: 'Suspensão Dianteira Completa' },
                'HE04R0': { tempo: 0.7, desc: 'Suporte do Farol' },
                'HM01R0': { tempo: 0.7, desc: 'Amortecedor Traseiro' },
                'HM05R0': { tempo: 0.3, desc: 'Tensor do Freio' },
                'HP02R0': { tempo: 1, desc: 'Pneu Dianteiro' },
                'HP03R0': { tempo: 1, desc: 'Pneu Traseiro' },
                'HP06R0': { tempo: 0.3, desc: 'Cubo da Roda Dianteira' },
                'HP07R0': { tempo: 0.4, desc: 'Cubo da Roda Traseira' },
                'HP10R0': { tempo: 0.5, desc: 'Rolamento da Roda Dianteira' },
                'HP11R0': { tempo: 0.7, desc: 'Rolamento da Roda Traseira' },
                'HP12R0': { tempo: 0.3, desc: 'Eixo da Roda Dianteira' },
                'HP13R0': { tempo: 0.4, desc: 'Eixo da Roda Traseira' },
                'LG01R0': { tempo: 1.3, desc: 'Mesa Inferior Direção' },
                'LG02R0': { tempo: 0.6, desc: 'Mesa Superior Direção' },
                'LG03R0': { tempo: 1, desc: 'Guiado um lado' },
                'MA02H0': { tempo: 0.7, desc: 'Cilindro Mestre de Freio OH' },
                'MA06R0': { tempo: 0.1, desc: 'Tampa do Reservatório' },
                'MF01R0': { tempo: 0.3, desc: 'Manete de Freio' },
                'MF03R0': { tempo: 0.4, desc: 'Pedal de Freio' },
                'MF04R0': { tempo: 0.3, desc: 'Cabo do Freio Dianteiro' },
                'MF06R0': { tempo: 0.4, desc: 'Mangueira do Freio Dianteiro' },
                'MJ01R0': { tempo: 0.3, desc: 'Pastilhas Freio Dianteiro' },
                'MJ02R0': { tempo: 0.5, desc: 'Eixo Acionador Freio Dianteiro' },
                'MJ03R0': { tempo: 0.5, desc: 'Acionador do Freio Dianteiro' },
                'MJ05R0': { tempo: 0.6, desc: 'Lona de Freio Traseiro' },
                'MJ06R0': { tempo: 0.6, desc: 'Eixo Acionador Freio Traseiro' },
                'MJ07R0': { tempo: 0.5, desc: 'Acionador do Freio Traseiro' },
                'MK01R0': { tempo: 0.4, desc: 'Disco de Freio Dianteiro' },
                'MK03H0': { tempo: 0.5, desc: 'Clipper de Freio Dianteiro' },
                'QJ02R0': { tempo: 0.1, desc: 'Espelho Retrovisor' },
                'RA01R0': { tempo: 5, desc: 'Chassi' },
                'RA02R0': { tempo: 0.2, desc: 'Tampa do Chassi' },
                'RA03R0': { tempo: 0.2, desc: 'Tampa da Rabeta' },
                'RB01R0': { tempo: 0.3, desc: 'Paralama Dianteiro' },
                'RB05R0': { tempo: 0.3, desc: 'Suporte do Paralama Dianteiro' },
                'RC01R0': { tempo: 0.2, desc: 'Assento' },
                'RD01R0': { tempo: 0.6, desc: 'Carenagem Completa' },
                'RF01R0': { tempo: 0.4, desc: 'Pedaleira Completa' },
                'RG01R0': { tempo: 0.5, desc: 'Descanso Central' },
                'RG02R0': { tempo: 0.2, desc: 'Descanso Lateral' },
                'SA01R0': { tempo: 0.2, desc: 'Farol Completo' },
                'SA04R0': { tempo: 0.3, desc: 'Lâmpada do Farol' },
                'SA05R0': { tempo: 0.3, desc: 'Seta Dianteira Completa' },
                'SA20R0': { tempo: 0.3, desc: 'Seta Traseira Completa' },
                'SB01R0': { tempo: 0.4, desc: 'Lanterna Traseira Completa' },
                'SD01R0': { tempo: 1.3, desc: 'Fiação Principal Completa' },
                'SD17R0': { tempo: 0.3, desc: 'Caixa de Fusíveis Completa' },
                'SE01R0': { tempo: 0.3, desc: 'Velocímetro Completo' },
                'SE03R0': { tempo: 0.4, desc: 'Tacômetro Completo' },
                'SF01R0': { tempo: 1.2, desc: 'Interruptor de Ignição Completo' },
                'SF02R0': { tempo: 0.4, desc: 'Interruptor do Punho LD' },
                'SF10R0': { tempo: 0.3, desc: 'Interruptor do Freio Dianteiro' },
                'SF11R0': { tempo: 0.5, desc: 'Interruptor do Freio Traseiro' },
                'SJ01R0': { tempo: 0.2, desc: 'Buzina' }
            },
            chopper150: {
                 'AA02H0': { tempo: 4.8, desc: 'Motor Completo OH' },
    'AA04R0': { tempo: 4.8, desc: 'Carcaça do Motor Completa' },
    'AB09R0': { tempo: 0.6, desc: 'Tampa Cabeote, Tampa Respiro' },
    'AB20R0': { tempo: 1.8, desc: 'Junta Cabeçote Completo um lado' },
    'AB21R0': { tempo: 1.5, desc: 'Junta do Cabeçote um lado' },
    'AC03R0': { tempo: 1.7, desc: 'Cilindro e Juntas Um lado' },
    'AE01R0': { tempo: 4.5, desc: 'Virabrequim' },
    'AE11R0': { tempo: 4.6, desc: 'Rolamento do Virabrequim LD' },
    'AE19R0': { tempo: 0.9, desc: 'Retentor do Virabrequim LD' },
    'AE20R0': { tempo: 0.6, desc: 'Retentor do Virabrequim LE' },
    'AE24R0': { tempo: 4.5, desc: 'Balanceiro do Virabrequim' },
    'AE27R0': { tempo: 1, desc: 'Engrenagem Primária do Virabrequim' },
    'AF01R0': { tempo: 1.9, desc: 'Pistão, Pino do Pistão e Anéis' },
    'AG02R0': { tempo: 1.8, desc: 'Válvula, Molas e Retentores' },
    'AG08R0': { tempo: 1, desc: 'Balanceiro de Válvulas' },
    'AH02R0': { tempo: 1.1, desc: 'Comando de Válvulas e Engrenagem' },
    'AH04R0': { tempo: 2.4, desc: 'Corrente de comando e Engrenagem' },
    'AH06R0': { tempo: 0.3, desc: 'Ajustador da Corrente de Comando um lado' },
    'AH13R0': { tempo: 1.2, desc: 'Tensor da Corrente de Comando um lado' },
    'BA01R0': { tempo: 0.7, desc: 'Bomba de óleo Completa' },
    'BA04R0': { tempo: 1, desc: 'Engrenagem Condutora da Bomba de óleo' },
    'BA05R0': { tempo: 0.6, desc: 'Engrenagem Conduzida da Bomba de óleo' },
    'BB02R0': { tempo: 0.2, desc: 'Filtro de óleo' },
    'BB04R0': { tempo: 0.4, desc: 'Tanque de óleo e Visor Nível de óleo' },
    'DA05R0': { tempo: 0.4, desc: 'Coletor de Admissão todos' },
    'DA15R0': { tempo: 0.3, desc: 'Cano de Escape Central um lado' },
    'DA26R0': { tempo: 0.3, desc: 'Escapamento um lado' },
    'DB01R0': { tempo: 0.4, desc: 'Filtro de Ar Completo' },
    'DB06R0': { tempo: 0.2, desc: 'Elemento Filtrante e Capa' },
    'DC02H0': { tempo: 0.6, desc: 'Carburador Completo OH' },
    'DC18R0': { tempo: 0.4, desc: 'Cabo do Afogador' },
    'DC25R0': { tempo: 0.6, desc: 'Cabo do Acelerador' },
    'DH01R0': { tempo: 0.4, desc: 'Tanque de Combustível' },
    'DH05R0': { tempo: 0.1, desc: 'Tampa do Tanque de Combustível' },
    'DH06R0': { tempo: 0.3, desc: 'Registro de Combustível' },
    'DH11R0': { tempo: 0.1, desc: 'Mangueira Combustível Registro-Carburador' },
    'EA01R0': { tempo: 0.2, desc: 'Bateria' },
    'EA02R0': { tempo: 0.4, desc: 'Suporte da Bateria' },
    'EA07R0': { tempo: 0.5, desc: 'Cabo Terra da Bateria' },
    'EB01R0': { tempo: 0.4, desc: 'Bobina de Ignição' },
    'EB09R0': { tempo: 0.3, desc: 'Unidade de Ignição' },
    'EB21R0': { tempo: 0.1, desc: 'Vela de Ignição todas' },
    'EB22R0': { tempo: 0.1, desc: 'Supressor de Vela todas' },
    'EE01R0': { tempo: 0.3, desc: 'Motor de Partida Completo' },
    'EE05R0': { tempo: 0.4, desc: 'Relé de Partida' },
    'EG01R0': { tempo: 0.6, desc: 'Rotor Magneto' },
    'EG03R0': { tempo: 0.7, desc: 'Estator' },
    'EG12R0': { tempo: 0.7, desc: 'Tampa do Magneto e Juntas' },
    'GA03R0': { tempo: 0.9, desc: 'Placa de Pressão, Discos e Separadores' },
    'GA06R0': { tempo: 1.3, desc: 'Embreagem Completa e Carcaça' },
    'GA27R0': { tempo: 0.8, desc: 'Tampa da Embreagem e Junta' },
    'GA28R0': { tempo: 0.6, desc: 'Cabo de Embreagem' },
    'GA32R0': { tempo: 0.4, desc: 'Manete de Embreagem' },
    'GB01R0': { tempo: 0.6, desc: 'Jogo de Embreagem de Partida' },
    'GB02R0': { tempo: 0.5, desc: 'Engrenagem e Eixo de Partida' },
    'GJ01R0': { tempo: 4.5, desc: 'Partes Internas da Transmissão todas' },
    'GK01R0': { tempo: 4.5, desc: 'Seletor de Marchas e Garfos' },
    'GK02R0': { tempo: 0.2, desc: 'Pedal de Câmbio' },
    'GK03R0': { tempo: 0.7, desc: 'Eixo do Pedal e Mola de Retorno' },
    'GS01R0': { tempo: 0.4, desc: 'Pinho do Motor' },
    'GS02R0': { tempo: 0.4, desc: 'Corrente de Transmissão' },
    'GS04R0': { tempo: 0.6, desc: 'Coroa de Transmissão' },
    'GS35R0': { tempo: 0.2, desc: 'Tampa do Pinho' },
    'GS36R0': { tempo: 0.2, desc: 'Capa da Corrente de Transmissão' },
    'HE01R0': { tempo: 1.2, desc: 'Suspensão Dianteira Completa' },
    'HE04R0': { tempo: 0.7, desc: 'Suporte do Farol um lado' },
    'HM01R0': { tempo: 0.2, desc: 'Amortecedor Traseiro Completo um lado' },
    'HM05R0': { tempo: 0.3, desc: 'Tensor do Freio' },
    'HP02R0': { tempo: 1, desc: 'Pneu Dianteiro um lado' },
    'HP03R0': { tempo: 1, desc: 'Pneu Traseiro um lado' },
    'HP06R0': { tempo: 2.2, desc: 'Cubo da Roda Dianteira' },
    'HP07R0': { tempo: 2.4, desc: 'Cubo da Roda Traseira' },
    'HP10R0': { tempo: 0.5, desc: 'Rolamento da Roda Dianteira todos' },
    'HP11R0': { tempo: 0.7, desc: 'Rolamento da Roda Traseira todos' },
    'HP12R0': { tempo: 0.3, desc: 'Eixo da Roda Dianteira' },
    'HP13R0': { tempo: 0.4, desc: 'Eixo da Roda Traseira' },
    'LG01R0': { tempo: 1.2, desc: 'Mesa Inferior Direção' },
    'LG02R0': { tempo: 0.6, desc: 'Mesa Superior Direção' },
    'LG03R0': { tempo: 0.5, desc: 'Guiado um lado' },
    'MA02H0': { tempo: 1, desc: 'Cilindro Mestre de Freio OH' },
    'MA06R0': { tempo: 0.1, desc: 'Tampa do Reservatório do Cilindro' },
    'MF01R0': { tempo: 0.2, desc: 'Manete de Freio' },
    'MF03R0': { tempo: 0.3, desc: 'Pedal de Freio' },
    'MF04R0': { tempo: 0.3, desc: 'Cabo do Freio Dianteiro um' },
    'MF06R0': { tempo: 0.4, desc: 'Mangueira do Freio Dianteiro N 1' },
    'MJ01R0': { tempo: 0.4, desc: 'Pastilha de Freio Dianteiro e Mola um lado' },
    'MJ05R0': { tempo: 0.6, desc: 'Lona de Freio Traseiro e Mola' },
    'MK01R0': { tempo: 0.4, desc: 'Disco de Freio Dianteiro um lado' },
    'MK03H0': { tempo: 0.6, desc: 'Clipper de Freio Dianteiro um lado OH' },
    'QJ02R0': { tempo: 0.1, desc: 'Espelho Retrovisor um lado' },
    'RA01R0': { tempo: 5, desc: 'Chassi' },
    'RA02R0': { tempo: 0.1, desc: 'Tampa do Chassi um lado' },
    'RB01R0': { tempo: 0.3, desc: 'Paralama Dianteiro' },
    'RB05R0': { tempo: 0.3, desc: 'Suporte do Paralama Dianteiro' },
    'RC01R0': { tempo: 0.2, desc: 'Assento' },
    'RD01R0': { tempo: 0.6, desc: 'Carenagem Completa' },
    'RF01R0': { tempo: 0.2, desc: 'Pedaleira Completa um lado' },
    'RG01R0': { tempo: 0.5, desc: 'Descanso Central' },
    'RG02R0': { tempo: 0.2, desc: 'Descanso Lateral' },
    'SA01R0': { tempo: 0.1, desc: 'Farol Completo um lado' },
    'SA04R0': { tempo: 0.3, desc: 'Lâmpada do Farol um lado' },
    'SA05R0': { tempo: 0.3, desc: 'Seta Dianteira Completa um lado' },
    'SA20R0': { tempo: 0.3, desc: 'Seta Traseira Completa um lado' },
    'SB01R0': { tempo: 0.3, desc: 'Lanterna Traseira Completa' },
    'SD01R0': { tempo: 0.8, desc: 'Fiação Principal Completa' },
    'SD17R0': { tempo: 0.2, desc: 'Caixa de Fusíveis Completa' },
    'SE01R0': { tempo: 0.5, desc: 'Velocímetro Completo' },
    'SE03R0': { tempo: 0.4, desc: 'Tacômetro Completo' },
    'SF01R0': { tempo: 0.8, desc: 'Interruptor de Ignição Completo' },
    'SF02R0': { tempo: 0.4, desc: 'Interruptor do Punho Completo LD' },
    'SF10R0': { tempo: 0.3, desc: 'Interruptor do Freio Dianteiro' },
    'SF11R0': { tempo: 0.2, desc: 'Interruptor do Freio Traseiro' },
    'SJ01R0': { tempo: 0.2, desc: 'Buzina' }
            },
            lindy: {
    'AA02H0': { tempo: 6, desc: 'Motor Completo OH' },
    'AA04R0': { tempo: 4.8, desc: 'Carcaça do Motor Completa' },
    'AB09R0': { tempo: 0.6, desc: 'Tampa Cabeote, Tampa Respiro' },
    'AB20R0': { tempo: 2.7, desc: 'Junta Cabeçote Completo um lado' },
    'AB21R0': { tempo: 2.4, desc: 'Junta do Cabeçote um lado' },
    'AC03R0': { tempo: 2.6, desc: 'Cilindro e Juntas Um lado' },
    'AE01R0': { tempo: 5.2, desc: 'Virabrequim' },
    'AE11R0': { tempo: 5.4, desc: 'Rolamento do Virabrequim LD' },
    'AE19R0': { tempo: 1.1, desc: 'Retentor do Virabrequim LD' },
    'AE20R0': { tempo: 0.8, desc: 'Retentor do Virabrequim LE' },
    'AE27R0': { tempo: 1.3, desc: 'Engrenagem Primária do Virabrequim' },
    'AF01R0': { tempo: 2.7, desc: 'Pistão, Pino do Pistão e Anéis' },
    'AG02R0': { tempo: 2.7, desc: 'Válvula, Molas e Retentores' },
    'AG08R0': { tempo: 2.1, desc: 'Balanceiro de Válvulas' },
    'AH02R0': { tempo: 2.2, desc: 'Comando de Válvulas e Engrenagem' },
    'AH04R0': { tempo: 3.1, desc: 'Corrente de Comando e Engrenagem' },
    'AH06R0': { tempo: 0.3, desc: 'Ajustador da Corrente de Comando um lado' },
    'AH13R0': { tempo: 2.2, desc: 'Tensor da Corrente de Comando um lado' },
    'BA01R0': { tempo: 0.9, desc: 'Bomba de óleo Completa' },
    'BA04R0': { tempo: 1, desc: 'Engrenagem Condutora da Bomba de óleo' },
    'BA05R0': { tempo: 0.8, desc: 'Engrenagem Conduzida da Bomba de óleo' },
    'BB02R0': { tempo: 0.2, desc: 'Filtro de óleo' },
    'BB04R0': { tempo: 0.8, desc: 'Tanque de óleo e Visor Nível de óleo' },
    'DA05R0': { tempo: 0.5, desc: 'Coletor de Admissão todos' },
    'DA15R0': { tempo: 0.4, desc: 'Cano de Escape Central um lado' },
    'DA26R0': { tempo: 0.4, desc: 'Escapamento um lado' },
    'DB01R0': { tempo: 0.3, desc: 'Filtro de Ar Completo' },
    'DB06R0': { tempo: 0.2, desc: 'Elemento Filtrante e Capa' },
    'DC02H0': { tempo: 0.7, desc: 'Carburador Completo OH' },
    'DC18R0': { tempo: 1.4, desc: 'Cabo do Afogador' },
    'DC25R0': { tempo: 1.4, desc: 'Cabo do Acelerador' },
    'DH01R0': { tempo: 1, desc: 'Tanque de Combustível' },
    'DH05R0': { tempo: 0.1, desc: 'Tampa do Tanque de Combustível' },
    'DH06R0': { tempo: 0.4, desc: 'Registro de Combustível' },
    'DH11R0': { tempo: 0.1, desc: 'Mangueira Combustível Registro-Carburador' },
    'EA01R0': { tempo: 0.3, desc: 'Bateria' },
    'EA02R0': { tempo: 0.8, desc: 'Suporte da Bateria' },
    'EA07R0': { tempo: 0.5, desc: 'Cabo Terra da Bateria' },
    'EB01R0': { tempo: 0.8, desc: 'Bobina de Ignição' },
    'EB09R0': { tempo: 0.7, desc: 'Unidade de Ignição' },
    'EB21R0': { tempo: 0.2, desc: 'Vela de Ignição todas' },
    'EB22R0': { tempo: 0.2, desc: 'Supressor de Vela todas' },
    'EE01R0': { tempo: 0.8, desc: 'Motor de Partida Completo' },
    'EE05R0': { tempo: 0.5, desc: 'Relé de Partida' },
    'EG01R0': { tempo: 0.6, desc: 'Rotor Magneto' },
    'EG03R0': { tempo: 0.7, desc: 'Estator' },
    'EG12R0': { tempo: 0.7, desc: 'Tampa do Magneto e Juntas' },
    'GA03R0': { tempo: 0.9, desc: 'Placa de Pressão, Discos e Separadores' },
    'GA06R0': { tempo: 2, desc: 'Embreagem Completa e Carcaça' },
    'GA27R0': { tempo: 1.2, desc: 'Tampa da Embreagem e Junta' },
    'GA28R0': { tempo: 0.6, desc: 'Cabo de Embreagem' },
    'GA32R0': { tempo: 0.4, desc: 'Manete de Embreagem' },
    'GB01R0': { tempo: 4.1, desc: 'Jogo de Embreagem de Partida' },
    'GB02R0': { tempo: 4.1, desc: 'Engrenagem e Eixo de Partida' },
    'GJ01R0': { tempo: 4.5, desc: 'Partes Internas da Transmissão todas' },
    'GK01R0': { tempo: 4.5, desc: 'Seletor de Marchas e Garfos' },
    'GK02R0': { tempo: 0.2, desc: 'Pedal de Câmbio' },
    'GK03R0': { tempo: 0.7, desc: 'Eixo do Pedal e Mola de Retorno' },
    'GS01R0': { tempo: 0.4, desc: 'Pinho do Motor' },
    'GS02R0': { tempo: 0.4, desc: 'Corrente de Transmissão' },
    'GS04R0': { tempo: 0.6, desc: 'Coroa de Transmissão' },
    'GS35R0': { tempo: 0.2, desc: 'Tampa do Pinho' },
    'GS36R0': { tempo: 0.2, desc: 'Capa da Corrente de Transmissão' },
    'HE01R0': { tempo: 1.7, desc: 'Suspensão Dianteira Completa' },
    'HE04R0': { tempo: 0.7, desc: 'Suporte do Farol um lado' },
    'HM01R0': { tempo: 0.7, desc: 'Amortecedor Traseiro Completo um lado' },
    'HM05R0': { tempo: 0.3, desc: 'Tensor do Freio' },
    'HP02R0': { tempo: 1, desc: 'Pneu Dianteiro um lado' },
    'HP03R0': { tempo: 0.9, desc: 'Pneu Traseiro um lado' },
    'HP06R0': { tempo: 0.3, desc: 'Cubo da Roda Dianteira' },
    'HP07R0': { tempo: 0.3, desc: 'Cubo da Roda Traseira' },
    'HP10R0': { tempo: 0.5, desc: 'Rolamento da Roda Dianteira todos' },
    'HP11R0': { tempo: 0.7, desc: 'Rolamento da Roda Traseira todos' },
    'HP12R0': { tempo: 0.3, desc: 'Eixo da Roda Dianteira' },
    'HP13R0': { tempo: 0.3, desc: 'Eixo da Roda Traseira' },
    'LG01R0': { tempo: 1.2, desc: 'Mesa Inferior Direção' },
    'LG02R0': { tempo: 0.6, desc: 'Mesa Superior Direção' },
    'LG03R0': { tempo: 0.5, desc: 'Guiado um lado' },
    'MA02H0': { tempo: 0.7, desc: 'Cilindro Mestre de Freio OH' },
    'MA06R0': { tempo: 0.1, desc: 'Tampa do Reservatório do Cilindro' },
    'MF01R0': { tempo: 0.2, desc: 'Manete de Freio' },
    'MF03R0': { tempo: 0.3, desc: 'Pedal de Freio' },
    'MF04R0': { tempo: 0.3, desc: 'Cabo do Freio Dianteiro um' },
    'MF06R0': { tempo: 0.4, desc: 'Mangueira do Freio Dianteiro N 1' },
    'MJ01R0': { tempo: 0.4, desc: 'Pastilha de Freio Dianteiro e Mola um lado' },
    'MJ05R0': { tempo: 0.3, desc: 'Lona de Freio Traseiro e Mola' },
    'MK01R0': { tempo: 0.4, desc: 'Disco de Freio Dianteiro um lado' },
    'MK03H0': { tempo: 0.5, desc: 'Clipper de Freio Dianteiro um lado OH' },
    'QJ02R0': { tempo: 0.1, desc: 'Espelho Retrovisor um lado' },
    'RA01R0': { tempo: 5.4, desc: 'Chassi' },
    'RA02R0': { tempo: 0.1, desc: 'Tampa do Chassi um lado' },
    'RB01R0': { tempo: 1.5, desc: 'Paralama Dianteiro' },
    'RB05R0': { tempo: 0.3, desc: 'Suporte do Paralama Dianteiro' },
    'RC01R0': { tempo: 0.4, desc: 'Assento' },
    'RD01R0': { tempo: 0.6, desc: 'Carenagem Completa' },
    'RF01R0': { tempo: 0.2, desc: 'Pedaleira Completa um lado' },
    'RG01R0': { tempo: 0.3, desc: 'Descanso Central' },
    'RG02R0': { tempo: 0.2, desc: 'Descanso Lateral' },
    'SA01R0': { tempo: 0.2, desc: 'Farol Completo um lado' },
    'SA04R0': { tempo: 0.3, desc: 'Lâmpada do Farol um lado' },
    'SA05R0': { tempo: 0.3, desc: 'Seta Dianteira Completa um lado' },
    'SA20R0': { tempo: 0.3, desc: 'Seta Traseira Completa um lado' },
    'SB01R0': { tempo: 0.3, desc: 'Lanterna Traseira Completa' },
    'SD01R0': { tempo: 0.8, desc: 'Fiação Principal Completa' },
    'SD17R0': { tempo: 0.2, desc: 'Caixa de Fusíveis Completa' },
    'SE01R0': { tempo: 0.5, desc: 'Velocímetro Completo' },
    'SE03R0': { tempo: 0.4, desc: 'Tacômetro Completo' },
    'SF01R0': { tempo: 0.8, desc: 'Interruptor de Ignição Completo' },
    'SF02R0': { tempo: 0.4, desc: 'Interruptor do Punho Completo LD' },
    'SF10R0': { tempo: 0.3, desc: 'Interruptor do Freio Dianteiro' },
    'SF11R0': { tempo: 0.2, desc: 'Interruptor do Freio Traseiro' },
    'SJ01R0': { tempo: 0.2, desc: 'Buzina' }
            },
            dk150: {
                 'AA02H0': { tempo: 4.8, desc: 'Motor Completo OH' },
    'AA04R0': { tempo: 1.3, desc: 'Carcaça do Motor Completa' },
    'AB09R0': { tempo: 0.6, desc: 'Tampa Cabeote, Tampa Respiro' },
    'AB20R0': { tempo: 1.8, desc: 'Junta Cabeçote Completo um lado' },
    'AB21R0': { tempo: 1.5, desc: 'Junta do Cabeçote um lado' },
    'AC03R0': { tempo: 1.7, desc: 'Cilindro e Juntas Um lado' },
    'AE01R0': { tempo: 4.5, desc: 'Virabrequim' },
    'AE11R0': { tempo: 4.6, desc: 'Rolamento do Virabrequim LD' },
    'AE12R0': { tempo: 4.6, desc: 'Rolamento do Virabrequim LE' },
    'AE19R0': { tempo: 0.9, desc: 'Retentor do Virabrequim LD' },
    'AE20R0': { tempo: 0.6, desc: 'Retentor do Virabrequim LE' },
    'AE27R0': { tempo: 1, desc: 'Engrenagem Primária do Virabrequim' },
    'AF01R0': { tempo: 1.9, desc: 'Pistão, Pino do Pistão e Anéis' },
    'AG02R0': { tempo: 1.8, desc: 'Válvula, Molas e Retentores' },
    'AG08R0': { tempo: 1, desc: 'Balanceiro de Válvulas' },
    'AH02R0': { tempo: 1.1, desc: 'Comando de Válvulas e Engrenagem' },
    'AH04R0': { tempo: 2.4, desc: 'Corrente de comando e Engrenagem' },
    'AH06R0': { tempo: 0.3, desc: 'Ajustador da Corrente de Comando um lado' },
    'AH13R0': { tempo: 1.2, desc: 'Tensor da Corrente de Comando um lado' },
    'BA01R0': { tempo: 0.7, desc: 'Bomba de óleo Completa' },
    'BA04R0': { tempo: 1, desc: 'Engrenagem Condutora da Bomba de óleo' },
    'BA05R0': { tempo: 0.6, desc: 'Engrenagem Conduzida da Bomba de óleo' },
    'BB02R0': { tempo: 0.2, desc: 'Filtro de óleo' },
    'BB04R0': { tempo: 0.4, desc: 'Tanque de óleo e Visor Nível de óleo' },
    'DA05R0': { tempo: 0.4, desc: 'Coletor de Admissão todos' },
    'DA15R0': { tempo: 0.3, desc: 'Cano de Escape Central um lado' },
    'DA26R0': { tempo: 0.3, desc: 'Escapamento um lado' },
    'DB01R0': { tempo: 0.4, desc: 'Filtro de Ar Completo' },
    'DB06R0': { tempo: 0.2, desc: 'Elemento Filtrante e Capa' },
    'DC02H0': { tempo: 0.6, desc: 'Carburador Completo OH' },
    'DC18R0': { tempo: 0.4, desc: 'Cabo do Afogador' },
    'DC25R0': { tempo: 0.6, desc: 'Cabo do Acelerador' },
    'DH01R0': { tempo: 0.4, desc: 'Tanque de Combustível' },
    'DH05R0': { tempo: 0.1, desc: 'Tampa do Tanque de Combustível' },
    'DH06R0': { tempo: 0.3, desc: 'Registro de Combustível' },
    'DH11R0': { tempo: 0.1, desc: 'Mangueira Combustível Registro-Carburador' },
    'EA01R0': { tempo: 0.2, desc: 'Bateria' },
    'EA02R0': { tempo: 0.4, desc: 'Suporte da Bateria' },
    'EA07R0': { tempo: 0.5, desc: 'Cabo Terra da Bateria' },
    'EB01R0': { tempo: 0.4, desc: 'Bobina de Ignição' },
    'EB09R0': { tempo: 0.3, desc: 'Unidade de Ignição' },
    'EB21R0': { tempo: 0.1, desc: 'Vela de Ignição todas' },
    'EB22R0': { tempo: 0.1, desc: 'Supressor de Vela todas' },
    'EE01R0': { tempo: 0.3, desc: 'Motor de Partida Completo' },
    'EE05R0': { tempo: 0.4, desc: 'Relé de Partida' },
    'EG01R0': { tempo: 0.6, desc: 'Rotor Magneto' },
    'EG03R0': { tempo: 0.7, desc: 'Estator' },
    'EG12R0': { tempo: 0.7, desc: 'Tampa do Magneto e Juntas' },
    'GA03R0': { tempo: 0.9, desc: 'Placa de Pressão, Discos e Separadores' },
    'GA27R0': { tempo: 0.8, desc: 'Tampa da Embreagem e Junta' },
    'GA28R0': { tempo: 0.6, desc: 'Cabo de Embreagem' },
    'GA32R0': { tempo: 0.4, desc: 'Manete de Embreagem' },
    'GB01R0': { tempo: 0.6, desc: 'Jogo de Embreagem de Partida' },
    'GB02R0': { tempo: 0.5, desc: 'Engrenagem e Eixo de Partida' },
    'GJ01R0': { tempo: 4.5, desc: 'Partes Internas da Transmissão todas' },
    'GJ05R0': { tempo: 0.2, desc: 'Eixo Traseiro' },
    'GK01R0': { tempo: 4.5, desc: 'Seletor de Marchas e Garfos' },
    'GK02R0': { tempo: 0.2, desc: 'Pedal de Câmbio' },
    'GK03R0': { tempo: 0.7, desc: 'Eixo do Pedal e Mola de Retorno' },
    'GS01R0': { tempo: 0.4, desc: 'Pinho do Motor' },
    'GS02R0': { tempo: 0.4, desc: 'Corrente de Transmissão' },
    'GS04R0': { tempo: 0.6, desc: 'Coroa de Transmissão' },
    'GS35R0': { tempo: 0.2, desc: 'Tampa do Pinho' },
    'GS36R0': { tempo: 0.2, desc: 'Capa da Corrente de Transmissão' },
    'HE01R0': { tempo: 1.2, desc: 'Suspensão Dianteira Completa' },
    'HE04R0': { tempo: 0.7, desc: 'Suporte do Farol um lado' },
    'HM01R0': { tempo: 0.2, desc: 'Amortecedor Traseiro Completo um lado' },
    'HM05R0': { tempo: 0.3, desc: 'Tensor do Freio' },
    'HP02R0': { tempo: 1, desc: 'Pneu Dianteiro um lado' },
    'HP03R0': { tempo: 1, desc: 'Pneu Traseiro um lado' },
    'HP06R0': { tempo: 2.2, desc: 'Cubo da Roda Dianteira' },
    'HP07R0': { tempo: 2.4, desc: 'Cubo da Roda Traseira' },
    'HP10R0': { tempo: 0.5, desc: 'Rolamento da Roda Dianteira todos' },
    'HP11R0': { tempo: 0.7, desc: 'Rolamento da Roda Traseira todos' },
    'HP12R0': { tempo: 0.3, desc: 'Eixo da Roda Dianteira' },
    'HP13R0': { tempo: 0.4, desc: 'Eixo da Roda Traseira' },
    'LG01R0': { tempo: 1.2, desc: 'Mesa Inferior Direção' },
    'LG02R0': { tempo: 0.6, desc: 'Mesa Superior Direção' },
    'LG03R0': { tempo: 0.5, desc: 'Guiado um lado' },
    'MA02H0': { tempo: 0.7, desc: 'Cilindro Mestre de Freio OH' },
    'MA06R0': { tempo: 0.1, desc: 'Tampa do Reservatório do Cilindro' },
    'MF01R0': { tempo: 0.2, desc: 'Manete de Freio' },
    'MF03R0': { tempo: 0.3, desc: 'Pedal de Freio' },
    'MF04R0': { tempo: 0.3, desc: 'Cabo do Freio Dianteiro um' },
    'MF06R0': { tempo: 0.4, desc: 'Mangueira do Freio Dianteiro N 1' },
    'MJ01R0': { tempo: 0.4, desc: 'Pastilha de Freio Dianteiro e Mola um lado' },
    'MJ05R0': { tempo: 0.6, desc: 'Lona de Freio Traseiro e Mola' },
    'MK01R0': { tempo: 0.4, desc: 'Disco de Freio Dianteiro um lado' },
    'MK03H0': { tempo: 0.5, desc: 'Clipper de Freio Dianteiro um lado OH' },
    'QJ02R0': { tempo: 0.1, desc: 'Espelho Retrovisor um lado' },
    'RA01R0': { tempo: 5, desc: 'Chassi' },
    'RA02R0': { tempo: 0.1, desc: 'Tampa do Chassi um lado' },
    'RB01R0': { tempo: 0.3, desc: 'Paralama Dianteiro' },
    'RB05R0': { tempo: 0.3, desc: 'Suporte do Paralama Dianteiro' },
    'RC01R0': { tempo: 0.2, desc: 'Assento' },
    'RD01R0': { tempo: 0.6, desc: 'Carenagem Completa' },
    'RF01R0': { tempo: 0.2, desc: 'Pedaleira Completa um lado' },
    'RG01R0': { tempo: 0.5, desc: 'Descanso Central' },
    'RG02R0': { tempo: 0.2, desc: 'Descanso Lateral' },
    'SA01R0': { tempo: 0.1, desc: 'Farol Completo um lado' },
    'SA04R0': { tempo: 0.3, desc: 'Lâmpada do Farol um lado' },
    'SA05R0': { tempo: 0.3, desc: 'Seta Dianteira Completa um lado' },
    'SA20R0': { tempo: 0.3, desc: 'Seta Traseira Completa um lado' },
    'SB01R0': { tempo: 0.3, desc: 'Lanterna Traseira Completa' },
    'SD01R0': { tempo: 0.8, desc: 'Fiação Principal Completa' },
    'SD17R0': { tempo: 0.2, desc: 'Caixa de Fusíveis Completa' },
    'SE01R0': { tempo: 0.5, desc: 'Velocímetro Completo' },
    'SE03R0': { tempo: 0.4, desc: 'Tacômetro Completo' },
    'SF01R0': { tempo: 0.8, desc: 'Interruptor de Ignição Completo' },
    'SF02R0': { tempo: 0.4, desc: 'Interruptor do Punho Completo LD' },
    'SF10R0': { tempo: 0.3, desc: 'Interruptor do Freio Dianteiro' },
    'SF11R0': { tempo: 0.2, desc: 'Interruptor do Freio Traseiro' },
    'SJ01R0': { tempo: 0.2, desc: 'Buzina' }
            },
            dk160: {
                 'AA02H0': { tempo: 4.8, desc: 'Motor Completo OH' },
    'AA04R0': { tempo: 1.3, desc: 'Carcaça do Motor Completa' },
    'AB09R0': { tempo: 0.6, desc: 'Tampa Cabeote, Tampa Respiro' },
    'AB20R0': { tempo: 1.8, desc: 'Junta Cabeçote Completo um lado' },
    'AB21R0': { tempo: 1.5, desc: 'Junta do Cabeçote um lado' },
    'AC03R0': { tempo: 1.7, desc: 'Cilindro e Juntas Um lado' },
    'AE01R0': { tempo: 4.5, desc: 'Virabrequim' },
    'AE11R0': { tempo: 4.6, desc: 'Rolamento do Virabrequim LD' },
    'AE12R0': { tempo: 4.6, desc: 'Rolamento do Virabrequim LE' },
    'AE19R0': { tempo: 0.9, desc: 'Retentor do Virabrequim LD' },
    'AE20R0': { tempo: 0.6, desc: 'Retentor do Virabrequim LE' },
    'AE27R0': { tempo: 1, desc: 'Engrenagem Primária do Virabrequim' },
    'AF01R0': { tempo: 1.9, desc: 'Pistão, Pino do Pistão e Anéis' },
    'AG02R0': { tempo: 1.8, desc: 'Válvula, Molas e Retentores' },
    'AG08R0': { tempo: 1, desc: 'Balanceiro de Válvulas' },
    'AH02R0': { tempo: 1.1, desc: 'Comando de Válvulas e Engrenagem' },
    'AH04R0': { tempo: 2.4, desc: 'Corrente de comando e Engrenagem' },
    'AH06R0': { tempo: 0.3, desc: 'Ajustador da Corrente de Comando um lado' },
    'AH13R0': { tempo: 1.2, desc: 'Tensor da Corrente de Comando um lado' },
    'BA01R0': { tempo: 0.7, desc: 'Bomba de óleo Completa' },
    'BA04R0': { tempo: 1, desc: 'Engrenagem Condutora da Bomba de óleo' },
    'BA05R0': { tempo: 0.6, desc: 'Engrenagem Conduzida da Bomba de óleo' },
    'BB02R0': { tempo: 0.2, desc: 'Filtro de óleo' },
    'BB04R0': { tempo: 0.4, desc: 'Tanque de óleo e Visor Nível de óleo' },
    'DA05R0': { tempo: 0.4, desc: 'Coletor de Admissão todos' },
    'DA15R0': { tempo: 0.3, desc: 'Cano de Escape Central um lado' },
    'DA26R0': { tempo: 0.3, desc: 'Escapamento um lado' },
    'DB01R0': { tempo: 0.4, desc: 'Filtro de Ar Completo' },
    'DB06R0': { tempo: 0.2, desc: 'Elemento Filtrante e Capa' },
    'DC02H0': { tempo: 0.6, desc: 'Carburador Completo OH' },
    'DC18R0': { tempo: 0.4, desc: 'Cabo do Afogador' },
    'DC25R0': { tempo: 0.6, desc: 'Cabo do Acelerador' },
    'DH01R0': { tempo: 0.4, desc: 'Tanque de Combustível' },
    'DH05R0': { tempo: 0.1, desc: 'Tampa do Tanque de Combustível' },
    'DH06R0': { tempo: 0.3, desc: 'Registro de Combustível' },
    'DH11R0': { tempo: 0.1, desc: 'Mangueira Combustível Registro-Carburador' },
    'EA01R0': { tempo: 0.2, desc: 'Bateria' },
    'EA02R0': { tempo: 0.4, desc: 'Suporte da Bateria' },
    'EA07R0': { tempo: 0.5, desc: 'Cabo Terra da Bateria' },
    'EB01R0': { tempo: 0.4, desc: 'Bobina de Ignição' },
    'EB09R0': { tempo: 0.3, desc: 'Unidade de Ignição' },
    'EB21R0': { tempo: 0.1, desc: 'Vela de Ignição todas' },
    'EB22R0': { tempo: 0.1, desc: 'Supressor de Vela todas' },
    'EE01R0': { tempo: 0.3, desc: 'Motor de Partida Completo' },
    'EE05R0': { tempo: 0.4, desc: 'Relé de Partida' },
    'EG01R0': { tempo: 0.6, desc: 'Rotor Magneto' },
    'EG03R0': { tempo: 0.7, desc: 'Estator' },
    'EG12R0': { tempo: 0.7, desc: 'Tampa do Magneto e Juntas' },
    'GA03R0': { tempo: 0.9, desc: 'Placa de Pressão, Discos e Separadores' },
    'GA27R0': { tempo: 0.8, desc: 'Tampa da Embreagem e Junta' },
    'GA28R0': { tempo: 0.6, desc: 'Cabo de Embreagem' },
    'GA32R0': { tempo: 0.4, desc: 'Manete de Embreagem' },
    'GB01R0': { tempo: 0.6, desc: 'Jogo de Embreagem de Partida' },
    'GB02R0': { tempo: 0.5, desc: 'Engrenagem e Eixo de Partida' },
    'GJ01R0': { tempo: 4.5, desc: 'Partes Internas da Transmissão todas' },
    'GJ05R0': { tempo: 0.2, desc: 'Eixo Traseiro' },
    'GK01R0': { tempo: 4.5, desc: 'Seletor de Marchas e Garfos' },
    'GK02R0': { tempo: 0.2, desc: 'Pedal de Câmbio' },
    'GK03R0': { tempo: 0.7, desc: 'Eixo do Pedal e Mola de Retorno' },
    'GS01R0': { tempo: 0.4, desc: 'Pinho do Motor' },
    'GS02R0': { tempo: 0.4, desc: 'Corrente de Transmissão' },
    'GS04R0': { tempo: 0.6, desc: 'Coroa de Transmissão' },
    'GS35R0': { tempo: 0.2, desc: 'Tampa do Pinho' },
    'GS36R0': { tempo: 0.2, desc: 'Capa da Corrente de Transmissão' },
    'HE01R0': { tempo: 1.2, desc: 'Suspensão Dianteira Completa' },
    'HE04R0': { tempo: 0.7, desc: 'Suporte do Farol um lado' },
    'HM01R0': { tempo: 0.2, desc: 'Amortecedor Traseiro Completo um lado' },
    'HM05R0': { tempo: 0.3, desc: 'Tensor do Freio' },
    'HP02R0': { tempo: 1, desc: 'Pneu Dianteiro um lado' },
    'HP03R0': { tempo: 1, desc: 'Pneu Traseiro um lado' },
    'HP06R0': { tempo: 2.2, desc: 'Cubo da Roda Dianteira' },
    'HP07R0': { tempo: 2.4, desc: 'Cubo da Roda Traseira' },
    'HP10R0': { tempo: 0.5, desc: 'Rolamento da Roda Dianteira todos' },
    'HP11R0': { tempo: 0.7, desc: 'Rolamento da Roda Traseira todos' },
    'HP12R0': { tempo: 0.3, desc: 'Eixo da Roda Dianteira' },
    'HP13R0': { tempo: 0.4, desc: 'Eixo da Roda Traseira' },
    'LG01R0': { tempo: 1.2, desc: 'Mesa Inferior Direção' },
    'LG02R0': { tempo: 0.6, desc: 'Mesa Superior Direção' },
    'LG03R0': { tempo: 0.5, desc: 'Guiado um lado' },
    'MA02H0': { tempo: 0.7, desc: 'Cilindro Mestre de Freio OH' },
    'MA06R0': { tempo: 0.1, desc: 'Tampa do Reservatório do Cilindro' },
    'MF01R0': { tempo: 0.2, desc: 'Manete de Freio' },
    'MF03R0': { tempo: 0.3, desc: 'Pedal de Freio' },
    'MF04R0': { tempo: 0.3, desc: 'Cabo do Freio Dianteiro um' },
    'MF06R0': { tempo: 0.4, desc: 'Mangueira do Freio Dianteiro N 1' },
    'MJ01R0': { tempo: 0.4, desc: 'Pastilha de Freio Dianteiro e Mola um lado' },
    'MJ05R0': { tempo: 0.6, desc: 'Lona de Freio Traseiro e Mola' },
    'MK01R0': { tempo: 0.4, desc: 'Disco de Freio Dianteiro um lado' },
    'MK03H0': { tempo: 0.5, desc: 'Clipper de Freio Dianteiro um lado OH' },
    'QJ02R0': { tempo: 0.1, desc: 'Espelho Retrovisor um lado' },
    'RA01R0': { tempo: 5, desc: 'Chassi' },
    'RA02R0': { tempo: 0.1, desc: 'Tampa do Chassi um lado' },
    'RB01R0': { tempo: 0.3, desc: 'Paralama Dianteiro' },
    'RB05R0': { tempo: 0.3, desc: 'Suporte do Paralama Dianteiro' },
    'RC01R0': { tempo: 0.2, desc: 'Assento' },
    'RD01R0': { tempo: 0.6, desc: 'Carenagem Completa' },
    'RF01R0': { tempo: 0.2, desc: 'Pedaleira Completa um lado' },
    'RG01R0': { tempo: 0.5, desc: 'Descanso Central' },
    'RG02R0': { tempo: 0.2, desc: 'Descanso Lateral' },
    'SA01R0': { tempo: 0.1, desc: 'Farol Completo um lado' },
    'SA04R0': { tempo: 0.3, desc: 'Lâmpada do Farol um lado' },
    'SA05R0': { tempo: 0.3, desc: 'Seta Dianteira Completa um lado' },
    'SA20R0': { tempo: 0.3, desc: 'Seta Traseira Completa um lado' },
    'SB01R0': { tempo: 0.3, desc: 'Lanterna Traseira Completa' },
    'SD01R0': { tempo: 0.8, desc: 'Fiação Principal Completa' },
    'SD17R0': { tempo: 0.2, desc: 'Caixa de Fusíveis Completa' },
    'SE01R0': { tempo: 0.5, desc: 'Velocímetro Completo' },
    'SE03R0': { tempo: 0.4, desc: 'Tacômetro Completo' },
    'SF01R0': { tempo: 0.8, desc: 'Interruptor de Ignição Completo' },
    'SF02R0': { tempo: 0.4, desc: 'Interruptor do Punho Completo LD' },
    'SF10R0': { tempo: 0.3, desc: 'Interruptor do Freio Dianteiro' },
    'SF11R0': { tempo: 0.2, desc: 'Interruptor do Freio Traseiro' },
    'SJ01R0': { tempo: 0.2, desc: 'Buzina' }
            },
            dr160: {
    'AA02H0': { tempo: 4.8, desc: 'Motor Completo OH' },
    'AA04R0': { tempo: 1.3, desc: 'Carcaça do Motor Completa' },
    'AB09R0': { tempo: 0.6, desc: 'Tampa Cabeote, Tampa Respiro' },
    'AB20R0': { tempo: 1.8, desc: 'Junta Cabeçote Completo um lado' },
    'AB21R0': { tempo: 1.5, desc: 'Junta do Cabeçote um lado' },
    'AC03R0': { tempo: 1.7, desc: 'Cilindro e Juntas Um lado' },
    'AE01R0': { tempo: 4.5, desc: 'Virabrequim' },
    'AE11R0': { tempo: 4.6, desc: 'Rolamento do Virabrequim LD' },
    'AE12R0': { tempo: 4.6, desc: 'Rolamento do Virabrequim LE' },
    'AE19R0': { tempo: 0.9, desc: 'Retentor do Virabrequim LD' },
    'AE20R0': { tempo: 0.6, desc: 'Retentor do Virabrequim LE' },
    'AE27R0': { tempo: 1, desc: 'Engrenagem Primária do Virabrequim' },
    'AF01R0': { tempo: 1.9, desc: 'Pistão, Pino do Pistão e Anéis' },
    'AG02R0': { tempo: 1.8, desc: 'Válvula, Molas e Retentores' },
    'AG08R0': { tempo: 1, desc: 'Balanceiro de Válvulas' },
    'AH02R0': { tempo: 1.1, desc: 'Comando de Válvulas e Engrenagem' },
    'AH04R0': { tempo: 2.4, desc: 'Corrente de comando e Engrenagem' },
    'AH06R0': { tempo: 0.3, desc: 'Ajustador da Corrente de Comando um lado' },
    'AH13R0': { tempo: 1.2, desc: 'Tensor da Corrente de Comando um lado' },
    'BA01R0': { tempo: 0.7, desc: 'Bomba de óleo Completa' },
    'BA04R0': { tempo: 1, desc: 'Engrenagem Condutora da Bomba de óleo' },
    'BA05R0': { tempo: 0.6, desc: 'Engrenagem Conduzida da Bomba de óleo' },
    'BB02R0': { tempo: 0.2, desc: 'Filtro de óleo' },
    'BB04R0': { tempo: 0.4, desc: 'Tanque de óleo e Visor Nível de óleo' },
    'DA05R0': { tempo: 0.4, desc: 'Coletor de Admissão todos' },
    'DA15R0': { tempo: 0.3, desc: 'Cano de Escape Central um lado' },
    'DA26R0': { tempo: 0.3, desc: 'Escapamento um lado' },
    'DB01R0': { tempo: 0.4, desc: 'Filtro de Ar Completo' },
    'DB06R0': { tempo: 0.2, desc: 'Elemento Filtrante e Capa' },
    'DC02H0': { tempo: 0.6, desc: 'Carburador Completo OH' },
    'DC18R0': { tempo: 0.4, desc: 'Cabo do Afogador' },
    'DC25R0': { tempo: 0.6, desc: 'Cabo do Acelerador' },
    'DH01R0': { tempo: 0.4, desc: 'Tanque de Combustível' },
    'DH05R0': { tempo: 0.1, desc: 'Tampa do Tanque de Combustível' },
    'DH06R0': { tempo: 0.3, desc: 'Registro de Combustível' },
    'DH11R0': { tempo: 0.1, desc: 'Mangueira Combustível Registro-Carburador' },
    'EA01R0': { tempo: 0.2, desc: 'Bateria' },
    'EA02R0': { tempo: 0.4, desc: 'Suporte da Bateria' },
    'EA07R0': { tempo: 0.5, desc: 'Cabo Terra da Bateria' },
    'EB01R0': { tempo: 0.4, desc: 'Bobina de Ignição' },
    'EB09R0': { tempo: 0.3, desc: 'Unidade de Ignição' },
    'EB21R0': { tempo: 0.1, desc: 'Vela de Ignição todas' },
    'EB22R0': { tempo: 0.1, desc: 'Supressor de Vela todas' },
    'EE01R0': { tempo: 0.3, desc: 'Motor de Partida Completo' },
    'EE05R0': { tempo: 0.4, desc: 'Relé de Partida' },
    'EG01R0': { tempo: 0.6, desc: 'Rotor Magneto' },
    'EG03R0': { tempo: 0.7, desc: 'Estator' },
    'EG12R0': { tempo: 0.7, desc: 'Tampa do Magneto e Juntas' },
    'GA03R0': { tempo: 0.9, desc: 'Placa de Pressão, Discos e Separadores' },
    'GA27R0': { tempo: 0.8, desc: 'Tampa da Embreagem e Junta' },
    'GA28R0': { tempo: 0.6, desc: 'Cabo de Embreagem' },
    'GA32R0': { tempo: 0.4, desc: 'Manete de Embreagem' },
    'GB01R0': { tempo: 0.6, desc: 'Jogo de Embreagem de Partida' },
    'GB02R0': { tempo: 0.5, desc: 'Engrenagem e Eixo de Partida' },
    'GJ01R0': { tempo: 4.5, desc: 'Partes Internas da Transmissão todas' },
    'GJ05R0': { tempo: 0.2, desc: 'Eixo Traseiro' },
    'GK01R0': { tempo: 4.5, desc: 'Seletor de Marchas e Garfos' },
    'GK02R0': { tempo: 0.2, desc: 'Pedal de Câmbio' },
    'GK03R0': { tempo: 0.7, desc: 'Eixo do Pedal e Mola de Retorno' },
    'GS01R0': { tempo: 0.4, desc: 'Pinho do Motor' },
    'GS02R0': { tempo: 0.4, desc: 'Corrente de Transmissão' },
    'GS04R0': { tempo: 0.6, desc: 'Coroa de Transmissão' },
    'GS35R0': { tempo: 0.2, desc: 'Tampa do Pinho' },
    'GS36R0': { tempo: 0.2, desc: 'Capa da Corrente de Transmissão' },
    'HE01R0': { tempo: 1.2, desc: 'Suspensão Dianteira Completa' },
    'HE04R0': { tempo: 0.7, desc: 'Suporte do Farol um lado' },
    'HM01R0': { tempo: 0.2, desc: 'Amortecedor Traseiro Completo um lado' },
    'HM05R0': { tempo: 0.3, desc: 'Tensor do Freio' },
    'HP02R0': { tempo: 1, desc: 'Pneu Dianteiro um lado' },
    'HP03R0': { tempo: 1, desc: 'Pneu Traseiro um lado' },
    'HP06R0': { tempo: 2.2, desc: 'Cubo da Roda Dianteira' },
    'HP07R0': { tempo: 2.4, desc: 'Cubo da Roda Traseira' },
    'HP10R0': { tempo: 0.5, desc: 'Rolamento da Roda Dianteira todos' },
    'HP11R0': { tempo: 0.7, desc: 'Rolamento da Roda Traseira todos' },
    'HP12R0': { tempo: 0.3, desc: 'Eixo da Roda Dianteira' },
    'HP13R0': { tempo: 0.4, desc: 'Eixo da Roda Traseira' },
    'LG01R0': { tempo: 1.2, desc: 'Mesa Inferior Direção' },
    'LG02R0': { tempo: 0.6, desc: 'Mesa Superior Direção' },
    'LG03R0': { tempo: 0.5, desc: 'Guiado um lado' },
    'MA02H0': { tempo: 0.7, desc: 'Cilindro Mestre de Freio OH' },
    'MA06R0': { tempo: 0.1, desc: 'Tampa do Reservatório do Cilindro' },
    'MF01R0': { tempo: 0.2, desc: 'Manete de Freio' },
    'MF03R0': { tempo: 0.3, desc: 'Pedal de Freio' },
    'MF04R0': { tempo: 0.3, desc: 'Cabo do Freio Dianteiro um' },
    'MF06R0': { tempo: 0.4, desc: 'Mangueira do Freio Dianteiro N 1' },
    'MJ01R0': { tempo: 0.4, desc: 'Pastilha de Freio Dianteiro e Mola um lado' },
    'MJ05R0': { tempo: 0.6, desc: 'Lona de Freio Traseiro e Mola' },
    'MK01R0': { tempo: 0.4, desc: 'Disco de Freio Dianteiro um lado' },
    'MK03H0': { tempo: 0.5, desc: 'Clipper de Freio Dianteiro um lado OH' },
    'QJ02R0': { tempo: 0.1, desc: 'Espelho Retrovisor um lado' },
    'RA01R0': { tempo: 5, desc: 'Chassi' },
    'RA02R0': { tempo: 0.1, desc: 'Tampa do Chassi um lado' },
    'RB01R0': { tempo: 0.3, desc: 'Paralama Dianteiro' },
    'RB05R0': { tempo: 0.3, desc: 'Suporte do Paralama Dianteiro' },
    'RC01R0': { tempo: 0.2, desc: 'Assento' },
    'RD01R0': { tempo: 0.6, desc: 'Carenagem Completa' },
    'RF01R0': { tempo: 0.2, desc: 'Pedaleira Completa um lado' },
    'RG01R0': { tempo: 0.5, desc: 'Descanso Central' },
    'RG02R0': { tempo: 0.2, desc: 'Descanso Lateral' },
    'SA01R0': { tempo: 0.1, desc: 'Farol Completo um lado' },
    'SA04R0': { tempo: 0.3, desc: 'Lâmpada do Farol um lado' },
    'SA05R0': { tempo: 0.3, desc: 'Seta Dianteira Completa um lado' },
    'SA20R0': { tempo: 0.3, desc: 'Seta Traseira Completa um lado' },
    'SB01R0': { tempo: 0.3, desc: 'Lanterna Traseira Completa' },
    'SD01R0': { tempo: 0.8, desc: 'Fiação Principal Completa' },
    'SD17R0': { tempo: 0.2, desc: 'Caixa de Fusíveis Completa' },
    'SE01R0': { tempo: 0.5, desc: 'Velocímetro Completo' },
    'SE03R0': { tempo: 0.4, desc: 'Tacômetro Completo' },
    'SF01R0': { tempo: 0.8, desc: 'Interruptor de Ignição Completo' },
    'SF02R0': { tempo: 0.4, desc: 'Interruptor do Punho Completo LD' },
    'SF10R0': { tempo: 0.3, desc: 'Interruptor do Freio Dianteiro' },
    'SF11R0': { tempo: 0.2, desc: 'Interruptor do Freio Traseiro' },
    'SJ01R0': { tempo: 0.2, desc: 'Buzina' },
    'outros': {tempo: 0.6, desc: 'ANTENA DO IMOBILIZADOR DR160 '},     },
            dl160: {
                'AA02H0': { tempo: 4.8, desc: 'Motor Completo OH' },
    'AA04R0': { tempo: 1.3, desc: 'Carcaça do Motor Completa' },
    'AB09R0': { tempo: 0.6, desc: 'Tampa Cabeote, Tampa Respiro' },
    'AB20R0': { tempo: 1.8, desc: 'Junta Cabeçote Completo um lado' },
    'AB21R0': { tempo: 1.5, desc: 'Junta do Cabeçote um lado' },
    'AC03R0': { tempo: 1.7, desc: 'Cilindro e Juntas Um lado' },
    'AE01R0': { tempo: 4.5, desc: 'Virabrequim' },
    'AE11R0': { tempo: 4.6, desc: 'Rolamento do Virabrequim LD' },
    'AE12R0': { tempo: 4.6, desc: 'Rolamento do Virabrequim LE' },
    'AE19R0': { tempo: 0.9, desc: 'Retentor do Virabrequim LD' },
    'AE20R0': { tempo: 0.6, desc: 'Retentor do Virabrequim LE' },
    'AE27R0': { tempo: 1, desc: 'Engrenagem Primária do Virabrequim' },
    'AF01R0': { tempo: 1.9, desc: 'Pistão, Pino do Pistão e Anéis' },
    'AG02R0': { tempo: 1.8, desc: 'Válvula, Molas e Retentores' },
    'AG08R0': { tempo: 1, desc: 'Balanceiro de Válvulas' },
    'AH02R0': { tempo: 1.1, desc: 'Comando de Válvulas e Engrenagem' },
    'AH04R0': { tempo: 2.4, desc: 'Corrente de comando e Engrenagem' },
    'AH06R0': { tempo: 0.3, desc: 'Ajustador da Corrente de Comando um lado' },
    'AH13R0': { tempo: 1.2, desc: 'Tensor da Corrente de Comando um lado' },
    'BA01R0': { tempo: 0.7, desc: 'Bomba de óleo Completa' },
    'BA04R0': { tempo: 1, desc: 'Engrenagem Condutora da Bomba de óleo' },
    'BA05R0': { tempo: 0.6, desc: 'Engrenagem Conduzida da Bomba de óleo' },
    'BB02R0': { tempo: 0.2, desc: 'Filtro de óleo' },
    'BB04R0': { tempo: 0.4, desc: 'Tanque de óleo e Visor Nível de óleo' },
    'DA05R0': { tempo: 0.4, desc: 'Coletor de Admissão todos' },
    'DA15R0': { tempo: 0.3, desc: 'Cano de Escape Central um lado' },
    'DA26R0': { tempo: 0.3, desc: 'Escapamento um lado' },
    'DB01R0': { tempo: 0.4, desc: 'Filtro de Ar Completo' },
    'DB06R0': { tempo: 0.2, desc: 'Elemento Filtrante e Capa' },
    'DC02H0': { tempo: 0.6, desc: 'Carburador Completo OH' },
    'DC18R0': { tempo: 0.4, desc: 'Cabo do Afogador' },
    'DC25R0': { tempo: 0.6, desc: 'Cabo do Acelerador' },
    'DH01R0': { tempo: 0.4, desc: 'Tanque de Combustível' },
    'DH05R0': { tempo: 0.1, desc: 'Tampa do Tanque de Combustível' },
    'DH06R0': { tempo: 0.3, desc: 'Registro de Combustível' },
    'DH11R0': { tempo: 0.1, desc: 'Mangueira Combustível Registro-Carburador' },
    'EA01R0': { tempo: 0.2, desc: 'Bateria' },
    'EA02R0': { tempo: 0.4, desc: 'Suporte da Bateria' },
    'EA07R0': { tempo: 0.5, desc: 'Cabo Terra da Bateria' },
    'EB01R0': { tempo: 0.4, desc: 'Bobina de Ignição' },
    'EB09R0': { tempo: 0.3, desc: 'Unidade de Ignição' },
    'EB21R0': { tempo: 0.1, desc: 'Vela de Ignição todas' },
    'EB22R0': { tempo: 0.1, desc: 'Supressor de Vela todas' },
    'EE01R0': { tempo: 0.3, desc: 'Motor de Partida Completo' },
    'EE05R0': { tempo: 0.4, desc: 'Relé de Partida' },
    'EG01R0': { tempo: 0.6, desc: 'Rotor Magneto' },
    'EG03R0': { tempo: 0.7, desc: 'Estator' },
    'EG12R0': { tempo: 0.7, desc: 'Tampa do Magneto e Juntas' },
    'GA03R0': { tempo: 0.9, desc: 'Placa de Pressão, Discos e Separadores' },
    'GA27R0': { tempo: 0.8, desc: 'Tampa da Embreagem e Junta' },
    'GA28R0': { tempo: 0.6, desc: 'Cabo de Embreagem' },
    'GA32R0': { tempo: 0.4, desc: 'Manete de Embreagem' },
    'GB01R0': { tempo: 0.6, desc: 'Jogo de Embreagem de Partida' },
    'GB02R0': { tempo: 0.5, desc: 'Engrenagem e Eixo de Partida' },
    'GJ01R0': { tempo: 4.5, desc: 'Partes Internas da Transmissão todas' },
    'GJ05R0': { tempo: 0.2, desc: 'Eixo Traseiro' },
    'GK01R0': { tempo: 4.5, desc: 'Seletor de Marchas e Garfos' },
    'GK02R0': { tempo: 0.2, desc: 'Pedal de Câmbio' },
    'GK03R0': { tempo: 0.7, desc: 'Eixo do Pedal e Mola de Retorno' },
    'GS01R0': { tempo: 0.4, desc: 'Pinho do Motor' },
    'GS02R0': { tempo: 0.4, desc: 'Corrente de Transmissão' },
    'GS04R0': { tempo: 0.6, desc: 'Coroa de Transmissão' },
    'GS35R0': { tempo: 0.2, desc: 'Tampa do Pinho' },
    'GS36R0': { tempo: 0.2, desc: 'Capa da Corrente de Transmissão' },
    'HE01R0': { tempo: 1.2, desc: 'Suspensão Dianteira Completa' },
    'HE04R0': { tempo: 0.7, desc: 'Suporte do Farol um lado' },
    'HM01R0': { tempo: 0.2, desc: 'Amortecedor Traseiro Completo um lado' },
    'HM05R0': { tempo: 0.3, desc: 'Tensor do Freio' },
    'HP02R0': { tempo: 1, desc: 'Pneu Dianteiro um lado' },
    'HP03R0': { tempo: 1, desc: 'Pneu Traseiro um lado' },
    'HP06R0': { tempo: 2.2, desc: 'Cubo da Roda Dianteira' },
    'HP07R0': { tempo: 2.4, desc: 'Cubo da Roda Traseira' },
    'HP10R0': { tempo: 0.5, desc: 'Rolamento da Roda Dianteira todos' },
    'HP11R0': { tempo: 0.7, desc: 'Rolamento da Roda Traseira todos' },
    'HP12R0': { tempo: 0.3, desc: 'Eixo da Roda Dianteira' },
    'HP13R0': { tempo: 0.4, desc: 'Eixo da Roda Traseira' },
    'LG01R0': { tempo: 1.2, desc: 'Mesa Inferior Direção' },
    'LG02R0': { tempo: 0.6, desc: 'Mesa Superior Direção' },
    'LG03R0': { tempo: 0.5, desc: 'Guiado um lado' },
    'MA02H0': { tempo: 0.7, desc: 'Cilindro Mestre de Freio OH' },
    'MA06R0': { tempo: 0.1, desc: 'Tampa do Reservatório do Cilindro' },
    'MF01R0': { tempo: 0.2, desc: 'Manete de Freio' },
    'MF03R0': { tempo: 0.3, desc: 'Pedal de Freio' },
    'MF04R0': { tempo: 0.3, desc: 'Cabo do Freio Dianteiro um' },
    'MF06R0': { tempo: 0.4, desc: 'Mangueira do Freio Dianteiro N 1' },
    'MJ01R0': { tempo: 0.4, desc: 'Pastilha de Freio Dianteiro e Mola um lado' },
    'MJ05R0': { tempo: 0.6, desc: 'Lona de Freio Traseiro e Mola' },
    'MK01R0': { tempo: 0.4, desc: 'Disco de Freio Dianteiro um lado' },
    'MK03H0': { tempo: 0.5, desc: 'Clipper de Freio Dianteiro um lado OH' },
    'QJ02R0': { tempo: 0.1, desc: 'Espelho Retrovisor um lado' },
    'RA01R0': { tempo: 5, desc: 'Chassi' },
    'RA02R0': { tempo: 0.1, desc: 'Tampa do Chassi um lado' },
    'RB01R0': { tempo: 0.3, desc: 'Paralama Dianteiro' },
    'RB05R0': { tempo: 0.3, desc: 'Suporte do Paralama Dianteiro' },
    'RC01R0': { tempo: 0.2, desc: 'Assento' },
    'RD01R0': { tempo: 0.6, desc: 'Carenagem Completa' },
    'RF01R0': { tempo: 0.2, desc: 'Pedaleira Completa um lado' },
    'RG01R0': { tempo: 0.5, desc: 'Descanso Central' },
    'RG02R0': { tempo: 0.2, desc: 'Descanso Lateral' },
    'SA01R0': { tempo: 0.1, desc: 'Farol Completo um lado' },
    'SA04R0': { tempo: 0.3, desc: 'Lâmpada do Farol um lado' },
    'SA05R0': { tempo: 0.3, desc: 'Seta Dianteira Completa um lado' },
    'SA20R0': { tempo: 0.3, desc: 'Seta Traseira Completa um lado' },
    'SB01R0': { tempo: 0.3, desc: 'Lanterna Traseira Completa' },
    'SD01R0': { tempo: 0.8, desc: 'Fiação Principal Completa' },
    'SD17R0': { tempo: 0.2, desc: 'Caixa de Fusíveis Completa' },
    'SE01R0': { tempo: 0.5, desc: 'Velocímetro Completo' },
    'SE03R0': { tempo: 0.4, desc: 'Tacômetro Completo' },
    'SF01R0': { tempo: 0.8, desc: 'Interruptor de Ignição Completo' },
    'SF02R0': { tempo: 0.4, desc: 'Interruptor do Punho Completo LD' },
    'SF10R0': { tempo: 0.3, desc: 'Interruptor do Freio Dianteiro' },
    'SF11R0': { tempo: 0.2, desc: 'Interruptor do Freio Traseiro' },
    'SJ01R0': { tempo: 0.2, desc: 'Buzina' }
            },
            nk150: {
                'AA02H0': { tempo: 4.8, desc: 'Motor Completo OH' },
    'AA04R0': { tempo: 1.3, desc: 'Carcaça do Motor Completa' },
    'AB09R0': { tempo: 0.6, desc: 'Tampa Cabeote, Tampa Respiro' },
    'AB20R0': { tempo: 1.8, desc: 'Junta Cabeçote Completo um lado' },
    'AB21R0': { tempo: 1.5, desc: 'Junta do Cabeçote um lado' },
    'AC03R0': { tempo: 1.7, desc: 'Cilindro e Juntas Um lado' },
    'AE01R0': { tempo: 4.5, desc: 'Virabrequim' },
    'AE11R0': { tempo: 4.6, desc: 'Rolamento do Virabrequim LD' },
    'AE12R0': { tempo: 4.6, desc: 'Rolamento do Virabrequim LE' },
    'AE19R0': { tempo: 0.9, desc: 'Retentor do Virabrequim LD' },
    'AE20R0': { tempo: 0.6, desc: 'Retentor do Virabrequim LE' },
    'AE27R0': { tempo: 1, desc: 'Engrenagem Primária do Virabrequim' },
    'AF01R0': { tempo: 1.9, desc: 'Pistão, Pino do Pistão e Anéis' },
    'AG02R0': { tempo: 1.8, desc: 'Válvula, Molas e Retentores' },
    'AG08R0': { tempo: 1, desc: 'Balanceiro de Válvulas' },
    'AH02R0': { tempo: 1.1, desc: 'Comando de Válvulas e Engrenagem' },
    'AH04R0': { tempo: 2.4, desc: 'Corrente de comando e Engrenagem' },
    'AH06R0': { tempo: 0.3, desc: 'Ajustador da Corrente de Comando um lado' },
    'AH13R0': { tempo: 1.2, desc: 'Tensor da Corrente de Comando um lado' },
    'BA01R0': { tempo: 0.7, desc: 'Bomba de óleo Completa' },
    'BA04R0': { tempo: 1, desc: 'Engrenagem Condutora da Bomba de óleo' },
    'BA05R0': { tempo: 0.6, desc: 'Engrenagem Conduzida da Bomba de óleo' },
    'BB02R0': { tempo: 0.2, desc: 'Filtro de óleo' },
    'BB04R0': { tempo: 0.4, desc: 'Tanque de óleo e Visor Nível de óleo' },
    'DA05R0': { tempo: 0.4, desc: 'Coletor de Admissão todos' },
    'DA15R0': { tempo: 0.3, desc: 'Cano de Escape Central um lado' },
    'DA26R0': { tempo: 0.3, desc: 'Escapamento um lado' },
    'DB01R0': { tempo: 0.4, desc: 'Filtro de Ar Completo' },
    'DB06R0': { tempo: 0.2, desc: 'Elemento Filtrante e Capa' },
    'DC02H0': { tempo: 0.6, desc: 'Carburador Completo OH' },
    'DC18R0': { tempo: 0.4, desc: 'Cabo do Afogador' },
    'DC25R0': { tempo: 0.6, desc: 'Cabo do Acelerador' },
    'DH01R0': { tempo: 0.4, desc: 'Tanque de Combustível' },
    'DH05R0': { tempo: 0.1, desc: 'Tampa do Tanque de Combustível' },
    'DH06R0': { tempo: 0.3, desc: 'Registro de Combustível' },
    'DH11R0': { tempo: 0.1, desc: 'Mangueira Combustível Registro-Carburador' },
    'EA01R0': { tempo: 0.2, desc: 'Bateria' },
    'EA02R0': { tempo: 0.4, desc: 'Suporte da Bateria' },
    'EA07R0': { tempo: 0.5, desc: 'Cabo Terra da Bateria' },
    'EB01R0': { tempo: 0.4, desc: 'Bobina de Ignição' },
    'EB09R0': { tempo: 0.3, desc: 'Unidade de Ignição' },
    'EB21R0': { tempo: 0.1, desc: 'Vela de Ignição todas' },
    'EB22R0': { tempo: 0.1, desc: 'Supressor de Vela todas' },
    'EE01R0': { tempo: 0.3, desc: 'Motor de Partida Completo' },
    'EE05R0': { tempo: 0.4, desc: 'Relé de Partida' },
    'EG01R0': { tempo: 0.6, desc: 'Rotor Magneto' },
    'EG03R0': { tempo: 0.7, desc: 'Estator' },
    'EG12R0': { tempo: 0.7, desc: 'Tampa do Magneto e Juntas' },
    'GA03R0': { tempo: 0.9, desc: 'Placa de Pressão, Discos e Separadores' },
    'GA27R0': { tempo: 0.8, desc: 'Tampa da Embreagem e Junta' },
    'GA28R0': { tempo: 0.6, desc: 'Cabo de Embreagem' },
    'GA32R0': { tempo: 0.4, desc: 'Manete de Embreagem' },
    'GB01R0': { tempo: 0.6, desc: 'Jogo de Embreagem de Partida' },
    'GB02R0': { tempo: 0.5, desc: 'Engrenagem e Eixo de Partida' },
    'GJ01R0': { tempo: 4.5, desc: 'Partes Internas da Transmissão todas' },
    'GJ05R0': { tempo: 0.2, desc: 'Eixo Traseiro' },
    'GK01R0': { tempo: 4.5, desc: 'Seletor de Marchas e Garfos' },
    'GK02R0': { tempo: 0.2, desc: 'Pedal de Câmbio' },
    'GK03R0': { tempo: 0.7, desc: 'Eixo do Pedal e Mola de Retorno' },
    'GS01R0': { tempo: 0.4, desc: 'Pinho do Motor' },
    'GS02R0': { tempo: 0.4, desc: 'Corrente de Transmissão' },
    'GS04R0': { tempo: 0.6, desc: 'Coroa de Transmissão' },
    'GS35R0': { tempo: 0.2, desc: 'Tampa do Pinho' },
    'GS36R0': { tempo: 0.2, desc: 'Capa da Corrente de Transmissão' },
    'HE01R0': { tempo: 1.2, desc: 'Suspensão Dianteira Completa' },
    'HE04R0': { tempo: 0.7, desc: 'Suporte do Farol um lado' },
    'HM01R0': { tempo: 0.2, desc: 'Amortecedor Traseiro Completo um lado' },
    'HM05R0': { tempo: 0.3, desc: 'Tensor do Freio' },
    'HP02R0': { tempo: 1, desc: 'Pneu Dianteiro um lado' },
    'HP03R0': { tempo: 1, desc: 'Pneu Traseiro um lado' },
    'HP06R0': { tempo: 2.2, desc: 'Cubo da Roda Dianteira' },
    'HP07R0': { tempo: 2.4, desc: 'Cubo da Roda Traseira' },
    'HP10R0': { tempo: 0.5, desc: 'Rolamento da Roda Dianteira todos' },
    'HP11R0': { tempo: 0.7, desc: 'Rolamento da Roda Traseira todos' },
    'HP12R0': { tempo: 0.3, desc: 'Eixo da Roda Dianteira' },
    'HP13R0': { tempo: 0.4, desc: 'Eixo da Roda Traseira' },
    'LG01R0': { tempo: 1.2, desc: 'Mesa Inferior Direção' },
    'LG02R0': { tempo: 0.6, desc: 'Mesa Superior Direção' },
    'LG03R0': { tempo: 0.5, desc: 'Guiado um lado' },
    'MA02H0': { tempo: 0.7, desc: 'Cilindro Mestre de Freio OH' },
    'MA06R0': { tempo: 0.1, desc: 'Tampa do Reservatório do Cilindro' },
    'MF01R0': { tempo: 0.2, desc: 'Manete de Freio' },
    'MF03R0': { tempo: 0.3, desc: 'Pedal de Freio' },
    'MF04R0': { tempo: 0.3, desc: 'Cabo do Freio Dianteiro um' },
    'MF06R0': { tempo: 0.4, desc: 'Mangueira do Freio Dianteiro N 1' },
    'MJ01R0': { tempo: 0.4, desc: 'Pastilha de Freio Dianteiro e Mola um lado' },
    'MJ05R0': { tempo: 0.6, desc: 'Lona de Freio Traseiro e Mola' },
    'MK01R0': { tempo: 0.4, desc: 'Disco de Freio Dianteiro um lado' },
    'MK03H0': { tempo: 0.5, desc: 'Clipper de Freio Dianteiro um lado OH' },
    'QJ02R0': { tempo: 0.1, desc: 'Espelho Retrovisor um lado' },
    'RA01R0': { tempo: 5, desc: 'Chassi' },
    'RA02R0': { tempo: 0.1, desc: 'Tampa do Chassi um lado' },
    'RB01R0': { tempo: 0.3, desc: 'Paralama Dianteiro' },
    'RB05R0': { tempo: 0.3, desc: 'Suporte do Paralama Dianteiro' },
    'RC01R0': { tempo: 0.2, desc: 'Assento' },
    'RD01R0': { tempo: 0.6, desc: 'Carenagem Completa' },
    'RF01R0': { tempo: 0.2, desc: 'Pedaleira Completa um lado' },
    'RG01R0': { tempo: 0.5, desc: 'Descanso Central' },
    'RG02R0': { tempo: 0.2, desc: 'Descanso Lateral' },
    'SA01R0': { tempo: 0.1, desc: 'Farol Completo um lado' },
    'SA04R0': { tempo: 0.3, desc: 'Lâmpada do Farol um lado' },
    'SA05R0': { tempo: 0.3, desc: 'Seta Dianteira Completa um lado' },
    'SA20R0': { tempo: 0.3, desc: 'Seta Traseira Completa um lado' },
    'SB01R0': { tempo: 0.3, desc: 'Lanterna Traseira Completa' },
    'SD01R0': { tempo: 0.8, desc: 'Fiação Principal Completa' },
    'SD17R0': { tempo: 0.2, desc: 'Caixa de Fusíveis Completa' },
    'SE01R0': { tempo: 0.5, desc: 'Velocímetro Completo' },
    'SE03R0': { tempo: 0.4, desc: 'Tacômetro Completo' },
    'SF01R0': { tempo: 0.8, desc: 'Interruptor de Ignição Completo' },
    'SF02R0': { tempo: 0.4, desc: 'Interruptor do Punho Completo LD' },
    'SF10R0': { tempo: 0.3, desc: 'Interruptor do Freio Dianteiro' },
    'SF11R0': { tempo: 0.2, desc: 'Interruptor do Freio Traseiro' },
    'SJ01R0': { tempo: 0.2, desc: 'Buzina' }
            },
            masterride150: {
                'AA02H0': { tempo: 4.8, desc: 'Motor Completo OH' },
    'AA04R0': { tempo: 1.3, desc: 'Carcaça do Motor Completa' },
    'AB09R0': { tempo: 0.6, desc: 'Tampa Cabeote, Tampa Respiro' },
    'AB20R0': { tempo: 1.8, desc: 'Junta Cabeçote Completo um lado' },
    'AB21R0': { tempo: 1.5, desc: 'Junta do Cabeçote um lado' },
    'AC03R0': { tempo: 1.7, desc: 'Cilindro e Juntas Um lado' },
    'AE01R0': { tempo: 4.5, desc: 'Virabrequim' },
    'AE11R0': { tempo: 4.6, desc: 'Rolamento do Virabrequim LD' },
    'AE12R0': { tempo: 4.6, desc: 'Rolamento do Virabrequim LE' },
    'AE19R0': { tempo: 0.9, desc: 'Retentor do Virabrequim LD' },
    'AE20R0': { tempo: 0.6, desc: 'Retentor do Virabrequim LE' },
    'AE27R0': { tempo: 1, desc: 'Engrenagem Primária do Virabrequim' },
    'AF01R0': { tempo: 1.9, desc: 'Pistão, Pino do Pistão e Anéis' },
    'AG02R0': { tempo: 1.8, desc: 'Válvula, Molas e Retentores' },
    'AG08R0': { tempo: 1, desc: 'Balanceiro de Válvulas' },
    'AH02R0': { tempo: 1.1, desc: 'Comando de Válvulas e Engrenagem' },
    'AH04R0': { tempo: 2.4, desc: 'Corrente de comando e Engrenagem' },
    'AH06R0': { tempo: 0.3, desc: 'Ajustador da Corrente de Comando um lado' },
    'AH13R0': { tempo: 1.2, desc: 'Tensor da Corrente de Comando um lado' },
    'BA01R0': { tempo: 0.7, desc: 'Bomba de óleo Completa' },
    'BA04R0': { tempo: 1, desc: 'Engrenagem Condutora da Bomba de óleo' },
    'BA05R0': { tempo: 0.6, desc: 'Engrenagem Conduzida da Bomba de óleo' },
    'BB02R0': { tempo: 0.2, desc: 'Filtro de óleo' },
    'BB04R0': { tempo: 0.4, desc: 'Tanque de óleo e Visor Nível de óleo' },
    'DA05R0': { tempo: 0.4, desc: 'Coletor de Admissão todos' },
    'DA15R0': { tempo: 0.3, desc: 'Cano de Escape Central um lado' },
    'DA26R0': { tempo: 0.3, desc: 'Escapamento um lado' },
    'DB01R0': { tempo: 0.4, desc: 'Filtro de Ar Completo' },
    'DB06R0': { tempo: 0.2, desc: 'Elemento Filtrante e Capa' },
    'DC02H0': { tempo: 0.6, desc: 'Carburador Completo OH' },
    'DC18R0': { tempo: 0.4, desc: 'Cabo do Afogador' },
    'DC25R0': { tempo: 0.6, desc: 'Cabo do Acelerador' },
    'DH01R0': { tempo: 0.4, desc: 'Tanque de Combustível' },
    'DH05R0': { tempo: 0.1, desc: 'Tampa do Tanque de Combustível' },
    'DH06R0': { tempo: 0.3, desc: 'Registro de Combustível' },
    'DH11R0': { tempo: 0.1, desc: 'Mangueira Combustível Registro-Carburador' },
    'EA01R0': { tempo: 0.2, desc: 'Bateria' },
    'EA02R0': { tempo: 0.4, desc: 'Suporte da Bateria' },
    'EA07R0': { tempo: 0.5, desc: 'Cabo Terra da Bateria' },
    'EB01R0': { tempo: 0.4, desc: 'Bobina de Ignição' },
    'EB09R0': { tempo: 0.3, desc: 'Unidade de Ignição' },
    'EB21R0': { tempo: 0.1, desc: 'Vela de Ignição todas' },
    'EB22R0': { tempo: 0.1, desc: 'Supressor de Vela todas' },
    'EE01R0': { tempo: 0.3, desc: 'Motor de Partida Completo' },
    'EE05R0': { tempo: 0.4, desc: 'Relé de Partida' },
    'EG01R0': { tempo: 0.6, desc: 'Rotor Magneto' },
    'EG03R0': { tempo: 0.7, desc: 'Estator' },
    'EG12R0': { tempo: 0.7, desc: 'Tampa do Magneto e Juntas' },
    'GA03R0': { tempo: 0.9, desc: 'Placa de Pressão, Discos e Separadores' },
    'GA27R0': { tempo: 0.8, desc: 'Tampa da Embreagem e Junta' },
    'GA28R0': { tempo: 0.6, desc: 'Cabo de Embreagem' },
    'GA32R0': { tempo: 0.4, desc: 'Manete de Embreagem' },
    'GB01R0': { tempo: 0.6, desc: 'Jogo de Embreagem de Partida' },
    'GB02R0': { tempo: 0.5, desc: 'Engrenagem e Eixo de Partida' },
    'GJ01R0': { tempo: 4.5, desc: 'Partes Internas da Transmissão todas' },
    'GJ05R0': { tempo: 0.2, desc: 'Eixo Traseiro' },
    'GK01R0': { tempo: 4.5, desc: 'Seletor de Marchas e Garfos' },
    'GK02R0': { tempo: 0.2, desc: 'Pedal de Câmbio' },
    'GK03R0': { tempo: 0.7, desc: 'Eixo do Pedal e Mola de Retorno' },
    'GS01R0': { tempo: 0.4, desc: 'Pinho do Motor' },
    'GS02R0': { tempo: 0.4, desc: 'Corrente de Transmissão' },
    'GS04R0': { tempo: 0.6, desc: 'Coroa de Transmissão' },
    'GS35R0': { tempo: 0.2, desc: 'Tampa do Pinho' },
    'GS36R0': { tempo: 0.2, desc: 'Capa da Corrente de Transmissão' },
    'HE01R0': { tempo: 1.2, desc: 'Suspensão Dianteira Completa' },
    'HE04R0': { tempo: 0.7, desc: 'Suporte do Farol um lado' },
    'HM01R0': { tempo: 0.2, desc: 'Amortecedor Traseiro Completo um lado' },
    'HM05R0': { tempo: 0.3, desc: 'Tensor do Freio' },
    'HP02R0': { tempo: 1, desc: 'Pneu Dianteiro um lado' },
    'HP03R0': { tempo: 1, desc: 'Pneu Traseiro um lado' },
    'HP06R0': { tempo: 2.2, desc: 'Cubo da Roda Dianteira' },
    'HP07R0': { tempo: 2.4, desc: 'Cubo da Roda Traseira' },
    'HP10R0': { tempo: 0.5, desc: 'Rolamento da Roda Dianteira todos' },
    'HP11R0': { tempo: 0.7, desc: 'Rolamento da Roda Traseira todos' },
    'HP12R0': { tempo: 0.3, desc: 'Eixo da Roda Dianteira' },
    'HP13R0': { tempo: 0.4, desc: 'Eixo da Roda Traseira' },
    'LG01R0': { tempo: 1.2, desc: 'Mesa Inferior Direção' },
    'LG02R0': { tempo: 0.6, desc: 'Mesa Superior Direção' },
    'LG03R0': { tempo: 0.5, desc: 'Guiado um lado' },
    'MA02H0': { tempo: 0.7, desc: 'Cilindro Mestre de Freio OH' },
    'MA06R0': { tempo: 0.1, desc: 'Tampa do Reservatório do Cilindro' },
    'MF01R0': { tempo: 0.2, desc: 'Manete de Freio' },
    'MF03R0': { tempo: 0.3, desc: 'Pedal de Freio' },
    'MF04R0': { tempo: 0.3, desc: 'Cabo do Freio Dianteiro um' },
    'MF06R0': { tempo: 0.4, desc: 'Mangueira do Freio Dianteiro N 1' },
    'MJ01R0': { tempo: 0.4, desc: 'Pastilha de Freio Dianteiro e Mola um lado' },
    'MJ05R0': { tempo: 0.6, desc: 'Lona de Freio Traseiro e Mola' },
    'MK01R0': { tempo: 0.4, desc: 'Disco de Freio Dianteiro um lado' },
    'MK03H0': { tempo: 0.5, desc: 'Clipper de Freio Dianteiro um lado OH' },
    'QJ02R0': { tempo: 0.1, desc: 'Espelho Retrovisor um lado' },
    'RA01R0': { tempo: 5, desc: 'Chassi' },
    'RA02R0': { tempo: 0.1, desc: 'Tampa do Chassi um lado' },
    'RB01R0': { tempo: 0.3, desc: 'Paralama Dianteiro' },
    'RB05R0': { tempo: 0.3, desc: 'Suporte do Paralama Dianteiro' },
    'RC01R0': { tempo: 0.2, desc: 'Assento' },
    'RD01R0': { tempo: 0.6, desc: 'Carenagem Completa' },
    'RF01R0': { tempo: 0.2, desc: 'Pedaleira Completa um lado' },
    'RG01R0': { tempo: 0.5, desc: 'Descanso Central' },
    'RG02R0': { tempo: 0.2, desc: 'Descanso Lateral' },
    'SA01R0': { tempo: 0.1, desc: 'Farol Completo um lado' },
    'SA04R0': { tempo: 0.3, desc: 'Lâmpada do Farol um lado' },
    'SA05R0': { tempo: 0.3, desc: 'Seta Dianteira Completa um lado' },
    'SA20R0': { tempo: 0.3, desc: 'Seta Traseira Completa um lado' },
    'SB01R0': { tempo: 0.3, desc: 'Lanterna Traseira Completa' },
    'SD01R0': { tempo: 0.8, desc: 'Fiação Principal Completa' },
    'SD17R0': { tempo: 0.2, desc: 'Caixa de Fusíveis Completa' },
    'SE01R0': { tempo: 0.5, desc: 'Velocímetro Completo' },
    'SE03R0': { tempo: 0.4, desc: 'Tacômetro Completo' },
    'SF01R0': { tempo: 0.8, desc: 'Interruptor de Ignição Completo' },
    'SF02R0': { tempo: 0.4, desc: 'Interruptor do Punho Completo LD' },
    'SF10R0': { tempo: 0.3, desc: 'Interruptor do Freio Dianteiro' },
    'SF11R0': { tempo: 0.2, desc: 'Interruptor do Freio Traseiro' },
    'SJ01R0': { tempo: 0.2, desc: 'Buzina' }
            }
        };

   // Cilindrada fictícia para esses veículos, ajuste conforme real
    const cilindradaPorModelo = {
        nex110: 110,
        chopper150: 150,
        lindy: 110,
        dk150: 150,
        dk160: 160,
        dr160: 160,
        dl160: 160,
        nk150: 150,
        masterride150: 150
        // Adicione mais entradas conforme necessário
    };

    // Valores novo cálculo para interna por cilindrada cc
    const valoresPorCilindrada = {
        interna: { 150: 66, 450: 132, 800: 192, 2000: 288 }, // max cc para faixa, usar <= comparação
        particular: { 150: 110, 450: 220, 800: 320, 2000: 480 },
        garantia:  { 150: 72, 450: 102, 800: 102, 2000: 102 }
    };

    function getValorPorCilindrada(cc, tipo) {
        if (tipo === "garantia") return valoresPorCilindrada.garantia;
        if (cc <= 150) return valoresPorCilindrada[tipo][150];
        if (cc <= 450) return valoresPorCilindrada[tipo][450];
        if (cc <= 800) return valoresPorCilindrada[tipo][800];
        return valoresPorCilindrada[tipo][2000];
    }

    function atualizarServicos() {
        const veiculo = document.getElementById('veiculo').value;
        const servico = document.getElementById('servico');
        servico.innerHTML = '<option value="">-- Primeiro selecione o veículo --</option>';
        servico.disabled = true;
        if (veiculo && tmoData[veiculo]) {
            Object.entries(tmoData[veiculo]).forEach(([codigo, data]) => {
                let opt = document.createElement('option');
                opt.value = codigo;
                opt.textContent = `${codigo} - ${data.desc} (${data.tempo}h)`;
                servico.appendChild(opt);
            });
            servico.disabled = false;
        }
        atualizarCilindrada();
        filtrarServicos();
    }

    function filtrarServicos() {
        const filtro = document.getElementById('searchServico').value.toLowerCase();
        const opcoes = document.querySelectorAll('#servico option:not([value=""])');
        let temVisiveis = false;
        opcoes.forEach(opt => {
            const texto = opt.textContent.toLowerCase();
            const show = texto.includes(filtro);
            opt.style.display = show ? '' : 'none';
            if(show) temVisiveis = true;
        });
        document.getElementById('servico').disabled = !temVisiveis && filtro.trim() !== '';
    }

    function atualizarCilindrada() {
        const veiculo = document.getElementById('veiculo').value;
        const tipo = document.getElementById('tipoServico').value;
        const info = document.getElementById('infoCilindrada');
        if (!veiculo) {
            info.style.display = 'none';
            document.getElementById('taxa').value = '';
            return;
        }
        const cc = cilindradaPorModelo[veiculo] || 150;
        const valor = getValorPorCilindrada(cc, tipo);
        info.style.display = 'block';
        document.getElementById('tipoServicoLabel').textContent = tipo.toUpperCase();
        document.getElementById('valorHora').textContent = `R$ ${valor}/h (Cilindrada: ${cc}cc)`;
        document.getElementById('taxa').value = valor;
    }

    function atualizarTaxa() {
        atualizarCilindrada();
    }

    function calcular() {
        const veiculo = document.getElementById('veiculo').value;
        const servicoCodigo = document.getElementById('servico').value;
        const taxa = parseFloat(document.getElementById('taxa').value);
        if (!veiculo) {
            alert('❌ Selecione o veículo!');
            return;
        }
        if (!servicoCodigo) {
            alert('❌ Selecione o serviço!');
            return;
        }
        if (isNaN(taxa) || taxa <= 0) {
            alert('❌ Taxa inválida!');
            return;
        }
        const dados = tmoData[veiculo]?.[servicoCodigo];
        if (!dados) {
            alert(`❌ TMO não encontrado para veículo ${veiculo.toUpperCase()} e serviço ${servicoCodigo}`);
            return;
        }
        const valorTotal = dados.tempo * taxa;
        document.getElementById('valorTotal').textContent = `R$ ${valorTotal.toFixed(2).replace('.', ',')}`;
        document.getElementById('detalhes').innerHTML = `
            Serviço: <strong>${dados.desc}</strong><br>
            Tempo: <strong>${dados.tempo}h</strong><br>
            Veículo: <strong>${veiculo.toUpperCase()}</strong><br>
        `;
        document.getElementById('resultado').style.display = 'block';
        document.getElementById('resultado').scrollIntoView({ behavior: 'smooth' });
    }

    // Inicializa ao carregar
    window.onload = () => {
        atualizarTaxa();
    };